# Generated by Django 5.0.1 on 2024-02-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
